@attr(tags=['advanced'], required_hardware='false')
def test_deployVM_in_sharedNetwork_scope_domain_withsubdomainaccess_ROOTuser(self):
    '\n\tValidate that regular user in ROOT domain is NOT allowed to deploy VM in a shared network created with scope="domain" and  with subdomain access for any domain\n\t'
    self.apiclient.connection.apiKey = self.user_roota_apikey
    self.apiclient.connection.securityKey = self.user_roota_secretkey
    self.vmdata['name'] = (self.acldata['vmROOTA']['name'] + '-shared-scope-domain-withsubdomainaccess')
    self.vmdata['displayname'] = (self.acldata['vmROOTA']['displayname'] + '-shared-scope-domain-withsubdomainaccess')
    try:
        vm = VirtualMachine.create(self.apiclient, self.vmdata, zoneid=self.zone.id, serviceofferingid=self.service_offering.id, templateid=self.template.id, networkids=self.shared_network_domain_with_subdomain_d11.id)
        self.fail("ROOT domain's user is able to deploy VM in a shared network with scope=domain with subdomain access ")
    except Exception as e:
        self.debug(('When a user from ROOT domain deploys a VM in a shared network with scope=domain with subdomain access %s' % e))
        if (not CloudstackAclException.verifyMsginException(e, CloudstackAclException.NOT_AVAILABLE_IN_DOMAIN)):
            self.fail("Error message validation failed when ROOT domain's user tries to deploy VM in a shared network with scope=domain with subdomain access")
