{
  try {
    exception2();
  }
 catch (  Exception e) {
    throw new CloudRuntimeException("exception",e);
  }
}
