@attr(tags=['advanced'], required_hardware='false')
def test_deployVM_in_sharedNetwork_scope_account_domainadminuser(self):
    '\n\tValidate that an admin user under the same domain but belonging to a different account is allowed to deploy VM in a shared network created with scope="account" for an account\n\n\t'
    self.apiclient.connection.apiKey = self.user_d111_apikey
    self.apiclient.connection.securityKey = self.user_d111_secretkey
    self.vmdata['name'] = (self.acldata['vmD111']['name'] + '-shared-scope-domain-withsubdomainaccess')
    self.vmdata['displayname'] = (self.acldata['vmD111']['displayname'] + '-shared-scope-domain-withsubdomainaccess')
    try:
        vm = VirtualMachine.create(self.apiclient, self.vmdata, zoneid=self.zone.id, serviceofferingid=self.service_offering.id, templateid=self.template.id, networkids=self.shared_network_account_d111a.id)
        self.fail('User from same domain but different account is able to deploy VM in a shared network with scope=account')
    except Exception as e:
        self.debug(('When a user from same domain but different account deploys a VM in a shared network with scope=account %s' % e))
        if (not CloudstackAclException.verifyMsginException(e, CloudstackAclException.UNABLE_TO_USE_NETWORK)):
            self.fail('Error message validation failed when User from same domain but different account tries to deploy VM in a shared network with scope=account')
