{
  try {
    callWithContext(new Callable<Object>(){
      @Override public Object call() throws Exception {
        run.run();
        return null;
      }
    }
);
  }
 catch (  Exception e) {
    ManagedContextUtils.rethrowException(e);
  }
}
