@attr(tags=['advanced', 'intervlan'])
def test_03_create_network_inside_range(self):
    ' Test create network inside cidr range of VPC\n        '
    self.debug('Creating a VPC offering')
    vpc_off = VpcOffering.create(self.apiclient, self.services['vpc_offering'])
    self._cleanup.append(vpc_off)
    self.validate_vpc_offering(vpc_off)
    self.debug('Enabling the VPC offering created')
    vpc_off.update(self.apiclient, state='Enabled')
    self.debug('creating a VPC network with cidr: 10.1.1.1/16')
    self.services['vpc']['cidr'] = '10.1.1.1/16'
    vpc = VPC.create(self.apiclient, self.services['vpc'], vpcofferingid=vpc_off.id, zoneid=self.zone.id, account=self.account.account.name, domainid=self.account.account.domainid)
    self.validate_vpc_network(vpc)
    self.debug('Creating network offering')
    self.network_offering = NetworkOffering.create(self.apiclient, self.services['network_offering'], conservemode=False)
    self.network_offering.update(self.apiclient, state='Enabled')
    self._cleanup.append(self.network_offering)
    self.debug("Creating network inside of the VPC's network")
    with self.assertRaises(Exception):
        self.services['network']['netmask'] = '255.0.0.0'
        Network.create(self.apiclient, self.services['network'], accountid=self.account.account.name, domainid=self.account.account.domainid, networkofferingid=self.network_offering.id, zoneid=self.zone.id, gateway='10.1.1.1', vpcid=vpc.id)
    self.debug('Network creation failed as network cidr range is inside of vpc')
    return
